import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import Navbar from "@/components/navbar/Navbar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (session == null) {
    return redirect("api/auth/signin");
  }

  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <TooltipProvider delayDuration={200}>
            <Navbar />
            {children}
          </TooltipProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
